steps:
  - label: "${BKTEC_STEP_LABEL}"
    command: "${BKTEC_STEP_COMMAND}"
    agents:
      queue: "default"
    parallelism: ${BUILDKITE_TEST_ENGINE_PARALLELISM}
    env:
      BUILDKITE_TEST_ENGINE_PLAN_IDENTIFIER: "${BUILDKITE_TEST_ENGINE_PLAN_IDENTIFIER}"
      BUILDKITE_TEST_ENGINE_SUITE_SLUG: "${BUILDKITE_TEST_ENGINE_SUITE_SLUG}"
      BUILDKITE_TEST_ENGINE_TEST_CMD: "${BUILDKITE_TEST_ENGINE_TEST_CMD}"
      BUILDKITE_TEST_ENGINE_RESULT_PATH: "${BUILDKITE_TEST_ENGINE_RESULT_PATH}"
      BUILDKITE_TEST_ENGINE_TEST_RUNNER: "${BUILDKITE_TEST_ENGINE_TEST_RUNNER}"
      BUILDKITE_TEST_ENGINE_TEST_FILE_PATTERN: "${BUILDKITE_TEST_ENGINE_TEST_FILE_PATTERN}"
      BUILDKITE_TEST_ENGINE_TEST_FILE_EXCLUDE_PATTERN: "${BUILDKITE_TEST_ENGINE_TEST_FILE_EXCLUDE_PATTERN}"
      BUILDKITE_TEST_ENGINE_RETRY_COUNT: "${BUILDKITE_TEST_ENGINE_RETRY_COUNT}"
