steps:
  - label: "Fetch timing data"
    command: .buildkite/steps/fetch_timing_data
    key: timing_data
    agents:
      queue: "default"

  - wait: ~

  - label: ":rspec: RSpec unit"
    command: .buildkite/steps/test.sh
    key: unit
    agents:
      queue: "default"
    parallelism: 5
    env:
      BUILDKITE_TEST_ENGINE_TEST_CMD: "bundle exec rspec {{testExamples}} --format progress --format json --out tmp/result.json"
      BUILDKITE_TEST_ENGINE_TEST_FILE_EXCLUDE_PATTERN: "spec/{acceptance,features}/**/*_spec.rb"
      BUILDKITE_TEST_ENGINE_SUITE_SLUG: "rspec"
      BUILDKITE_TEST_ENGINE_RETRY_COUNT: 1
      BUILDKITE_TEST_ENGINE_RESULT_PATH: "tmp/result.json"
      BUILDKITE_TEST_ENGINE_TEST_RUNNER: rspec
      BUILDKITE_TEST_ENGINE_SPLIT_BY_EXAMPLE: true

  - label: ":chromium: Feature Specs"
    command: .buildkite/steps/feature-tests.sh
    key: acceptance
    agents:
      queue: "default"
    parallelism: 10
    env:
      BUILDKITE_TEST_ENGINE_TEST_FILE_PATTERN: "spec/{acceptance,features}/**/*_spec.rb"
      BUILDKITE_TEST_ENGINE_SUITE_SLUG: "feature-tests"
      BUILDKITE_TEST_ENGINE_TEST_CMD: "bundle exec rspec {{testExamples}} --format progress --format json --out tmp/result.json"
      BUILDKITE_TEST_ENGINE_RETRY_COUNT: 1
      BUILDKITE_TEST_ENGINE_RESULT_PATH: "tmp/result.json"
      BUILDKITE_TEST_ENGINE_TEST_RUNNER: rspec
      BUILDKITE_TEST_ENGINE_SPLIT_BY_EXAMPLE: true

  - label: "Update Test Ownership?"
    branches: "main"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: ./TESTOWNERS
              config:
                trigger: update-test-ownership
