steps:
  - label: "Fetch timing data"
    command: .buildkite/steps/fetch_timing_data
    key: timing_data
    agents:
      queue: "default"

  - wait: ~

  - label: ":rspec: RSpec unit"
    command: .buildkite/steps/test.sh
    key: unit
    agents:
      queue: "default"
    parallelism: 2
    env:
      BUILDKITE_TEST_ENGINE_TEST_FILE_PATTERN: "spec/models/**/*_spec.rb"

  - label: "Acceptance"
    command: .buildkite/steps/test.sh
    key: acceptance
    agents:
      queue: "default"
    parallelism: 2
    env:
      BUILDKITE_TEST_ENGINE_TEST_FILE_PATTERN: "spec/{acceptance,features}/**/*_spec.rb"

  - label: "Everything Else"
    command: .buildkite/steps/test.sh
    key: everything_else
    agents:
      queue: "default"
    parallelism: 2
    env:
      BUILDKITE_TEST_ENGINE_TEST_FILE_EXCLUDE_PATTERN: "spec/{acceptance,features,models}/**/*_spec.rb"

  - label: "Update Test Ownership?"
    branches: "main"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: ./TESTOWNERS
              config:
                trigger: update-test-ownership
