steps:
  - label: "Fetch timing data"
    command: .buildkite/steps/fetch_timing_data
    key: timing_data
    agents:
      queue: "hosted-queue"

  - wait: ~

  - label: ":rspec: RSpec unit"
    command: .buildkite/steps/test.sh
    key: unit
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_PATTERN: "spec/unit/**/*_spec.rb"

  - label: "Acceptance"
    command: .buildkite/steps/test.sh
    key: acceptance
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_PATTERN: "spec/acceptance/**/*_spec.rb"

  - label: "Everything Else"
    command: .buildkite/steps/test.sh
    key: everything_else
    agents:
      queue: "hosted-queue"
    parallelism: 2
    env:
      BUILDKITE_SPLITTER_TEST_FILE_EXCLUDE_PATTERN: "spec/{acceptance,unit}/**/*_spec.rb"

  - label: "Update Test Ownership?"
    branches: "main"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: ./TESTOWNERS
              config:
                trigger: update-test-ownership
